[package]
name = "sasl"
version = "0.4.1"
authors = ["lumi <lumi@pew.im>"]
description = "A crate for SASL authentication. Currently only does the client side."
homepage = "https://gitlab.com/lumi/sasl-rs"
repository = "https://gitlab.com/lumi/sasl-rs"
documentation = "https://docs.rs/sasl"
readme = "README.md"
keywords = ["sasl", "authentication"]
license = "LGPL-3.0+"

[badges]
gitlab = { repository = "lumi/sasl-rs" }

[features]
default = ["scram"]
scram = ["openssl"]

[dependencies]
base64 = "0.9.1"

[dependencies.openssl]
version = "0.10.7"
optional = true
